include: package:flutter_lints/flutter.yaml

linter:

  rules:
    # errors rules
    - avoid_empty_else
    - avoid_dynamic_calls
    - avoid_relative_lib_imports
    - avoid_init_to_null
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - control_flow_in_finally
    # - diagnostic_describe_all_properties  => passing object instead of duplicating
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    # - omit_local_variable_types => not needed (you have to change all local variables to var insted of specific type)
    - overridden_fields
    - package_api_docs
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_single_quotes
    # - prefer_spread_collections
    # - prefer_typing_uninitialized_variables
    # - prefer_void_to_null
    # - provide_deprecation_message
    # - recursive_getters
    # - slash_for_doc_comments
    # - sort_unnamed_constructors_first
    # - test_types_in_equals
    # - throw_in_finally
    # - type_annotate_public_apis
    # - type_init_formals
    # - unawaited_futures
    # - unnecessary_brace_in_string_interps
    # - unnecessary_const
    # - unnecessary_getters_setters
    # - unnecessary_lambdas
    # - unnecessary_new
    # - unnecessary_null_aware_assignments
    # - unnecessary_null_in_if_null_operators
    # - unnecessary_overrides




     



