name: taktikat
description: A new Flutter project.

publish_to: 'none'

version: 3.0.5+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  get: ^4.6.5
  logger: ^1.1.0
  shared_preferences: ^2.0.17
  flutter_screenutil: ^5.6.0
  dio: ^5.0.1
  flutter_svg: ^2.0.2
  cached_network_image: ^3.2.3
  lazy_load_scrollview: ^1.3.0
  smooth_page_indicator: ^1.0.1
  sms_autofill: ^2.3.0
  google_sign_in: ^6.0.1
  flutter_facebook_auth: ^5.0.8
  sign_in_with_apple: ^4.3.0
  twitter_login: ^4.3.1
  expandable: ^5.0.1
  pin_code_fields: ^7.4.0
  image_picker: ^0.8.6+4
  flutter_carousel_slider: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/fonts/
    - assets/images/
    - assets/gifs/

  fonts:
  - family: droid kufi
    fonts:
      - asset: assets/fonts/DROIDKUFI-BOLD.TTF
        weight: 700
      - asset: assets/fonts/DROIDKUFI-REGULAR.TTF
        weight: 300
      - asset: assets/fonts/DROIDKUFI-REGULAR.TTF
        weight: 500
      - asset: assets/fonts/DROIDKUFI-REGULAR.TTF
        weight: 100

